apiVersion: v1
kind: ConfigMap
metadata:
  name: ignite-config
data:
  ignite-configuration.xml: |
    <bean class="org.apache.ignite.configuration.IgniteConfiguration">
        <!-- Enable metrics -->
        <property name="metricsUpdateFrequency" value="10000"/>
        <property name="metricExporterSpi">
            <bean class="org.apache.ignite.spi.metric.jmx.JmxMetricExporterSpi"/>
        </property>
    </bean>
